# Generated by Django 5.0.6 on 2025-06-11 01:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="student_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="userphoto",
            name="photo",
            field=models.ImageField(upload_to=core.models.user_photo_upload_path),
        ),
    ]
