# Generated by Django 5.0.6 on 2025-06-12 11:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_systembalance_total_disbursed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="student_number",
            new_name="idnumber",
        ),
    ]
