# Generated by Django 5.0.6 on 2025-06-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_rename_student_number_user_idnumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="landlord_gcash_number",
            field=models.CharField(
                blank=True,
                help_text="If requesting rent aid, optional landlord GCash number.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="priority",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=0,
                help_text="Automatically set based on need_type.",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="proof_of_need",
            field=models.FileField(
                blank=True,
                help_text="PDF/image proof required for all non-food requests.",
                null=True,
                upload_to="uploads/proof/",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="purpose_of_travel",
            field=models.TextField(
                blank=True,
                help_text="(Required for Transport requests) Describe purpose of travel.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="willing_partial",
            field=models.BooleanField(
                default=False,
                help_text="Check if you’re willing to accept partial assistance.",
            ),
        ),
    ]
