# Generated by Django 5.0.6 on 2025-06-24 08:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_claim_landlord_gcash_number_claim_priority_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="proof_of_need",
            field=models.FileField(
                blank=True,
                help_text="PDF/image proof required for non-food requests.",
                null=True,
                upload_to=core.models.proof_photo_upload_path,
            ),
        ),
    ]
